CREATE TABLE example(
id INTEGER NOT NULL,
name VARCHAR(200),
last VARCHAR(200),
phone VARCHAR(200),
PRIMARY KEY(id)
);

CREATE TABLE example2(
id INTEGER NOT NULL,
id2 INTEGER NOT NULL,
name VARCHAR(200),
last VARCHAR(200),
phone VARCHAR(200),
PRIMARY KEY(id)
);